# The next line to define a global platform for your project
 platform :ios, '12.0'
 use_frameworks!

def testing_pod
  # This pods are included in test target only
  pod 'Quick'
  pod 'Nimble'
  
end

def common_pod
  # This pods are included in test target and main target also
  
end

target 'AdvanceNetworkApp' do
  
  pod 'SDWebImage', '~> 5.0'
  pod 'IHProgressHUD'
  common_pod

end

target 'AdvanceNetworkAppTests' do
 testing_pod
 common_pod
end
